@url = https://8080-matheusmora-atividadefi-k5c9t7rpt83.ws-us116.gitpod.io

@token =

###
GET {{url}}/tarefas
Authorization: Bearer {{token}}

###
GET {{url}}/tarefas/1
Authorization: Bearer {{token}}

###
POST {{url}}/tarefas
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "titulo": "Título OPK",
    "descricao": "Descrição ABC",
    "dataInicio": "2024-11-10",
    "dataConclusao": "2024-11-20"
}

###
PUT {{url}}/tarefas/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "titulo": "Título OPK  - Alterado"
}

###
DELETE {{url}}/tarefas/1
Authorization: Bearer {{token}}

###
POST {{url}}/tarefas/1/colaboradores/1
Authorization: Bearer {{token}}

###
DELETE {{url}}/tarefas/1/colaboradores/1
Authorization: Bearer {{token}}